DEFAULT_STREAM_NAME = "signal-stream"
DEFAULT_SET_NAME = "signal-stream-set"
DEFAULT_REDIS_PORT = "6379"
DEFAULT_REDIS_DB = 1
DEFAULT_REDIS_HOST = "localhost"
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_HEADERS = {}
