[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "shared"
version = "0.1.0"
description = "The shared package for the attack-radar data pipeline"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "redis>=6.4.0",
]
